### ISSUE TITLE
Error when building images after v0.9.3

### ISSUE THREAD

**Issue by jjcfrancisco** [urbica/martin#1021]
Hi,

I cannot build images for the following versions: `v0.10.0`, `v0.11.0` & `v0.11.3`. I've tested it in a M1 macbook `arm64` & in a ubuntu `amd64` virtual machine and get the same issue. **I have no issues when building `v0.9.3`**.

This is what I used to build the images:
```bash
docker build -t martin .
```

Stdout when built in `arm64`:
```bash
#0 162.8 error: failed to run custom build command for `pbf_font_tools v2.5.0`
#0 162.8 
#0 162.8 Caused by:
#0 162.8   process didn't exit successfully: `/usr/src/martin/target/release/build/pbf_font_tools-49699dd4207ff108/build-script-build` (exit status: 101)
#0 162.8   --- stderr
#0 162.8   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/pbf_font_tools-2.5.0/build.rs:12:19:
#0 162.8   Protobuf codegen failed.: parse and typecheck
#0 162.8 
#0 162.8   Caused by:
#0 162.8       0: using protoc parser
#0 162.8       1: failed to spawn command `"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/protoc-bin-vendored-linux-aarch_64-3.0.0/bin/protoc" "-Iproto/" "--descriptor_set_out=/tmp/protobuf-parseCiYWsZ/descriptor.pbbin" "--include_imports" "proto/glyphs.proto"`
#0 162.8       2: No such file or directory (os error 2)
#0 162.8   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#0 162.8 warning: build failed, waiting for other jobs to finish...
------
Dockerfile:9
--------------------
   7 |     
   8 |     COPY . .
   9 | >>> RUN CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo build --release
  10 |     
  11 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo build --release" did not complete successfully: exit code: 101
```

Stdout when built in `amd64`:
```bash
error: failed to run custom build command for `pbf_font_tools v2.5.0`

Caused by:
  process didn't exit successfully: `/usr/src/martin/target/release/build/pbf_font_tools-07218ef84cc2063c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/pbf_font_tools-2.5.0/build.rs:12:19:
  Protobuf codegen failed.: parse and typecheck

  Caused by:
      0: using protoc parser
      1: failed to spawn command `"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/protoc-bin-vendored-linux-x86_64-3.0.0/bin/protoc" "-Iproto/" "--descriptor_set_out=/tmp/protobuf-parsegjO6yF/descriptor.pbbin" "--include_imports" "proto/glyphs.proto"`
      2: No such file or directory (os error 2)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
The command '/bin/sh -c CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo build --release' returned a non-zero code: 101
```

Seems to be linked to the inclusion of `pbf_font_tools`?

**Comment by nyurik** [comment]
@jjcfrancisco thx for reporting!   I am a bit surprised that you are building the docker image yourself - the Dockerfile was left in the repo by accident, and is no longer used by the CI/CD. Is there a reason you want to do that, rather than use `ghcr.io/maplibre/martin` image?

**Comment by jjcfrancisco** [comment]
Hi @nyurik, I can certainly use the image from `ghcr.io/maplibre/martin`. To be completely honest, I haven't payed much attention to it, I just saw the `Dockerfile` in the repository and has been working ok until now. My suggestion would be either to remove the `Dockerfile` or fix the issue in order to remove confusion. Thanks agains the the quick response 🙏

**Comment by nyurik** [comment]
Thanks, I was worried there was some usecase we didn't cover in the current build ecosystem.  I have removed the dockerfile in #1022
